// Generated C++ code from Pascal-like algorithm: HelloWorld
// Original algorithm: HelloWorld

// Generated by Pascal-like to C++ Compiler
// DO NOT EDIT THIS FILE DIRECTLY

#include <iostream>
#include <cmath>
#include <string>
using namespace std;

int main() {
    cout << "Hello, World!" << endl;

    return 0;
}

