// Generated C++ code from Pascal-like algorithm: TestIf
// Original algorithm: TestIf

// Generated by Pascal-like to C++ Compiler
// DO NOT EDIT THIS FILE DIRECTLY

#include <iostream>
#include <cmath>
#include <string>
using namespace std;

// Global variables
int x = 0;

int main() {
    x = 7;
    if (x > 5) {
        cout << "x is greater than 5" << endl;
    } else {
        cout << "x is less or equal to 5" << endl;
    }

    return 0;
}

