// Generated C++ code from Pascal-like algorithm: Ex14_DatabaseSystem
// Original algorithm: Ex14_DatabaseSystem

// Generated by Pascal-like to C++ Compiler
// DO NOT EDIT THIS FILE DIRECTLY

#include <iostream>
#include <cmath>
#include <string>
using namespace std;

// Global variables
int id1 = 0;
int id2 = 0;
int id3 = 0;
int id4 = 0;
int id5 = 0;
std::string name1 = "";
std::string name2 = "";
std::string name3 = "";
std::string name4 = "";
std::string name5 = "";
int age1 = 0;
int age2 = 0;
int age3 = 0;
int age4 = 0;
int age5 = 0;
double salary1 = 0;
double salary2 = 0;
double salary3 = 0;
double salary4 = 0;
double salary5 = 0;
int recordCount = 0;
int choice = 0;
int searchId = 0;
bool found = false;
int i = 0;

int findRecordById(int searchId);
double calculateAverageSalary();
double calculateAverageAge();
void addRecord(int& id, std::string& name, int& age, double& salary, int recNum);
void printRecord(int id, std::string name, int age, double salary);
void deleteRecord(int recordNum);
void printAllRecords();

int main() {
    id1 = 0;
    id2 = 0;
    id3 = 0;
    id4 = 0;
    id5 = 0;
    name1 = "";
    name2 = "";
    name3 = "";
    name4 = "";
    name5 = "";
    age1 = 0;
    age2 = 0;
    age3 = 0;
    age4 = 0;
    age5 = 0;
    salary1 = 0.0;
    salary2 = 0.0;
    salary3 = 0.0;
    salary4 = 0.0;
    salary5 = 0.0;
    recordCount = 0;
    choice = 0;
    while (choice != 7) {
        cout << "" << endl;
        cout << "===== DATABASE MANAGEMENT SYSTEM =====" << endl;
        cout << "1. Add Record" << endl;
        cout << "2. View All Records" << endl;
        cout << "3. Search Record by ID" << endl;
        cout << "4. Delete Record" << endl;
        cout << "5. Statistics" << endl;
        cout << "6. Clear All Records" << endl;
        cout << "7. Exit" << endl;
        cout << "======================================" << endl;
        cout << "Enter your choice:" << endl;
        cin >> choice;
        if (choice == 1) {
            if (recordCount < 5) {
                recordCount = recordCount + 1;
                if (id1 == 0) {
                    addRecord(id1, name1, age1, salary1, 1);
                } else {
                    if (id2 == 0) {
                        addRecord(id2, name2, age2, salary2, 2);
                    } else {
                        if (id3 == 0) {
                            addRecord(id3, name3, age3, salary3, 3);
                        } else {
                            if (id4 == 0) {
                                addRecord(id4, name4, age4, salary4, 4);
                            } else {
                                if (id5 == 0) {
                                    addRecord(id5, name5, age5, salary5, 5);
                                } else {
                                    cout << "Database is full! Maximum 5 records." << endl;
                                    recordCount = recordCount - 1;
                                }
                            }
                        }
                    }
                }
            } else {
                cout << "Database is full! Maximum 5 records." << endl;
            }
        } else {
            if (choice == 2) {
                printAllRecords();
            } else {
                if (choice == 3) {
                    cout << "Enter ID to search:" << endl;
                    cin >> searchId;
                    i = findRecordById(searchId);
                    if (i > 0) {
                        cout << "Record found:" << endl;
                        if (i == 1) {
                            printRecord(id1, name1, age1, salary1);
                        }
                        if (i == 2) {
                            printRecord(id2, name2, age2, salary2);
                        }
                        if (i == 3) {
                            printRecord(id3, name3, age3, salary3);
                        }
                        if (i == 4) {
                            printRecord(id4, name4, age4, salary4);
                        }
                        if (i == 5) {
                            printRecord(id5, name5, age5, salary5);
                        }
                    } else {
                        cout << "Record not found with ID: " << endl;
                        cout << searchId << endl;
                    }
                } else {
                    if (choice == 4) {
                        cout << "Enter ID to delete:" << endl;
                        cin >> searchId;
                        i = findRecordById(searchId);
                        if (i > 0) {
                            deleteRecord(i);
                        } else {
                            cout << "Record not found with ID: " << endl;
                            cout << searchId << endl;
                        }
                    } else {
                        if (choice == 5) {
                            cout << "===== DATABASE STATISTICS =====" << endl;
                            cout << "Total Records: " << endl;
                            cout << recordCount << endl;
                            cout << "Maximum Capacity: 5" << endl;
                            cout << "Available Slots: " << endl;
                            cout << 5 - recordCount << endl;
                            if (recordCount > 0) {
                                cout << "Average Age: " << endl;
                                cout << calculateAverageAge() << endl;
                                cout << "Average Salary: $" << endl;
                                cout << calculateAverageSalary() << endl;
                                cout << "Salary Range: $" << endl;
                                cout << calculateAverageSalary() * 0.8 << endl;
                                cout << " - $" << endl;
                                cout << calculateAverageSalary() * 1.2 << endl;
                            }
                            cout << "===============================" << endl;
                        } else {
                            if (choice == 6) {
                                id1 = 0;
                                name1 = "";
                                age1 = 0;
                                salary1 = 0.0;
                                id2 = 0;
                                name2 = "";
                                age2 = 0;
                                salary2 = 0.0;
                                id3 = 0;
                                name3 = "";
                                age3 = 0;
                                salary3 = 0.0;
                                id4 = 0;
                                name4 = "";
                                age4 = 0;
                                salary4 = 0.0;
                                id5 = 0;
                                name5 = "";
                                age5 = 0;
                                salary5 = 0.0;
                                recordCount = 0;
                                cout << "All records cleared!" << endl;
                            } else {
                                if (choice == 7) {
                                    cout << "Thank you for using the Database System!" << endl;
                                } else {
                                    cout << "Invalid choice! Please try again." << endl;
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    return 0;
}

int findRecordById(int searchId) {
    if (id1 == searchId) {
        return 1;
    }
    if (id2 == searchId) {
        return 2;
    }
    if (id3 == searchId) {
        return 3;
    }
    if (id4 == searchId) {
        return 4;
    }
    if (id5 == searchId) {
        return 5;
    }
    return 0;
}

double calculateAverageSalary() {
    // Variable declarations
    double sum;
    int count;

    sum = 0.0;
    count = 0;
    if (id1 != 0) {
        sum = sum + salary1;
        count = count + 1;
    }
    if (id2 != 0) {
        sum = sum + salary2;
        count = count + 1;
    }
    if (id3 != 0) {
        sum = sum + salary3;
        count = count + 1;
    }
    if (id4 != 0) {
        sum = sum + salary4;
        count = count + 1;
    }
    if (id5 != 0) {
        sum = sum + salary5;
        count = count + 1;
    }
    if (count > 0) {
        return sum / count;
    } else {
        return 0.0;
    }
    return 0.0;
}

double calculateAverageAge() {
    // Variable declarations
    int sum;
    int count;

    sum = 0;
    count = 0;
    if (id1 != 0) {
        sum = sum + age1;
        count = count + 1;
    }
    if (id2 != 0) {
        sum = sum + age2;
        count = count + 1;
    }
    if (id3 != 0) {
        sum = sum + age3;
        count = count + 1;
    }
    if (id4 != 0) {
        sum = sum + age4;
        count = count + 1;
    }
    if (id5 != 0) {
        sum = sum + age5;
        count = count + 1;
    }
    if (count > 0) {
        return sum / count;
    } else {
        return 0.0;
    }
    return 0.0;
}

void addRecord(int& id, std::string& name, int& age, double& salary, int recNum) {
    cout << "Enter ID for record " << endl;
    cout << recNum << endl;
    cout << ":" << endl;
    cin >> id;
    cout << "Enter Name:" << endl;
    cin >> name;
    cout << "Enter Age:" << endl;
    cin >> age;
    cout << "Enter Salary:" << endl;
    cin >> salary;
    cout << "Record added successfully!" << endl;
}

void printRecord(int id, std::string name, int age, double salary) {
    cout << "----------------------" << endl;
    cout << "ID: " << endl;
    cout << id << endl;
    cout << "Name: " << endl;
    cout << name << endl;
    cout << "Age: " << endl;
    cout << age << endl;
    cout << "Salary: $" << endl;
    cout << salary << endl;
    cout << "----------------------" << endl;
}

void deleteRecord(int recordNum) {
    if (recordNum == 1) {
        id1 = 0;
        name1 = "";
        age1 = 0;
        salary1 = 0.0;
    } else {
        if (recordNum == 2) {
            id2 = 0;
            name2 = "";
            age2 = 0;
            salary2 = 0.0;
        } else {
            if (recordNum == 3) {
                id3 = 0;
                name3 = "";
                age3 = 0;
                salary3 = 0.0;
            } else {
                if (recordNum == 4) {
                    id4 = 0;
                    name4 = "";
                    age4 = 0;
                    salary4 = 0.0;
                } else {
                    if (recordNum == 5) {
                        id5 = 0;
                        name5 = "";
                        age5 = 0;
                        salary5 = 0.0;
                    }
                }
            }
        }
    }
    recordCount = recordCount - 1;
    cout << "Record deleted successfully!" << endl;
}

void printAllRecords() {
    cout << "===== ALL RECORDS =====" << endl;
    cout << "Total Records: " << endl;
    cout << recordCount << endl;
    cout << "" << endl;
    if (id1 != 0) {
        printRecord(id1, name1, age1, salary1);
    }
    if (id2 != 0) {
        printRecord(id2, name2, age2, salary2);
    }
    if (id3 != 0) {
        printRecord(id3, name3, age3, salary3);
    }
    if (id4 != 0) {
        printRecord(id4, name4, age4, salary4);
    }
    if (id5 != 0) {
        printRecord(id5, name5, age5, salary5);
    }
    if (recordCount > 0) {
        cout << "" << endl;
        cout << "Statistics:" << endl;
        cout << "Average Age: " << endl;
        cout << calculateAverageAge() << endl;
        cout << "Average Salary: $" << endl;
        cout << calculateAverageSalary() << endl;
    }
    cout << "=======================" << endl;
}

