// Generated C++ code from Pascal-like algorithm: TestStructureSmall
// Original algorithm: TestStructureSmall

// Generated by Pascal-like to C++ Compiler
// DO NOT EDIT THIS FILE DIRECTLY

#include <iostream>
#include <cmath>
#include <string>
using namespace std;

struct Point {
    int x = 0;
    int y = 0;
};

// Global variables
Point p;

int main() {
    p.x = 10;
    p.y = 20;
    cout << "point x:" << endl;
    cout << p.x << endl;
    cout << "point y:" << endl;
    cout << p.y << endl;

    return 0;
}

