// Generated C++ code from Pascal-like algorithm: TestMatrixSmall
// Original algorithm: TestMatrixSmall

// Generated by Pascal-like to C++ Compiler
// DO NOT EDIT THIS FILE DIRECTLY

#include <iostream>
#include <cmath>
#include <string>
using namespace std;

// Global variables
int m[2][2];
int total = 0;

int main() {
    m[0][0] = 1;
    m[0][1] = 2;
    m[1][0] = 3;
    m[1][1] = 4;
    total = ((m[0][0] + m[0][1]) + m[1][0]) + m[1][1];
    cout << "matrix total:" << endl;
    cout << total << endl;

    return 0;
}

