// Generated C++ code from Pascal-like algorithm: TestStructure
// Original algorithm: TestStructure

// Generated by Pascal-like to C++ Compiler
// DO NOT EDIT THIS FILE DIRECTLY

#include <iostream>
#include <cmath>
#include <string>
using namespace std;

struct Person {
    std::string name = "";
    int age = 0;
    double salary = 0;
};

// Global variables
Person p;

int main() {
    p.name = "Alice";
    p.age = 30;
    p.salary = 4500.5;
    cout << "Employee:" << endl;
    cout << p.name << endl;
    cout << p.age << endl;
    cout << p.salary << endl;

    return 0;
}

