// Generated C++ code from Pascal-like algorithm: TestWhile
// Original algorithm: TestWhile

// Generated by Pascal-like to C++ Compiler
// DO NOT EDIT THIS FILE DIRECTLY

#include <iostream>
#include <cmath>
#include <string>
using namespace std;

// Global variables
int i = 0;

int main() {
    i = 0;
    while (i < 3) {
        cout << "i:" << endl;
        cout << i << endl;
        i = i + 1;
    }

    return 0;
}

