// Generated C++ code from Pascal-like algorithm: TestFunction
// Original algorithm: TestFunction

// Generated by Pascal-like to C++ Compiler
// DO NOT EDIT THIS FILE DIRECTLY

#include <iostream>
#include <cmath>
#include <string>
using namespace std;

// Global variables
int n = 0;
int result = 0;

int square(int x);

int main() {
    n = 6;
    result = square(n);
    cout << "square:" << endl;
    cout << result << endl;

    return 0;
}

int square(int x) {
    return x * x;
}

