// Generated C++ code from Pascal-like algorithm: TestRepeat
// Original algorithm: TestRepeat

// Generated by Pascal-like to C++ Compiler
// DO NOT EDIT THIS FILE DIRECTLY

#include <iostream>
#include <cmath>
#include <string>
using namespace std;

// Global variables
int i = 0;

int main() {
    i = 3;
    do {
        cout << "i:" << endl;
        cout << i << endl;
        i = i - 1;
    } while (!(i == 0));

    return 0;
}

