// Generated C++ code from Pascal-like algorithm: TestMatrix
// Original algorithm: TestMatrix

// Generated by Pascal-like to C++ Compiler
// DO NOT EDIT THIS FILE DIRECTLY

#include <iostream>
#include <cmath>
#include <string>
using namespace std;

// Global variables
int m[2][3];
int i = 0;
int j = 0;
int sum = 0;

int main() {
    m[0][0] = 1;
    m[0][1] = 2;
    m[0][2] = 3;
    m[1][0] = 4;
    m[1][1] = 5;
    m[1][2] = 6;
    sum = 0;
    for (int i = 0; i <= 1; i++) {
        for (int j = 0; j <= 2; j++) {
            sum = sum + m[i][j];
        }
    }
    cout << "Matrix sum:" << endl;
    cout << sum << endl;

    return 0;
}

