// Generated C++ code from Pascal-like algorithm: TestAllFeatures
// Original algorithm: TestAllFeatures

// Generated by Pascal-like to C++ Compiler
// DO NOT EDIT THIS FILE DIRECTLY

#include <iostream>
#include <cmath>
#include <string>
using namespace std;

struct Student {
    std::string name = "";
    int age = 0;
    double grade = 0;
};

// Global variables
int x = 0;
int y = 0;
int z = 0;
int i = 0;
int j = 0;
int sum = 0;
double average = 0;
bool isPassed = false;
std::string message = "";
int nums[5];
int mat[2][3];
Student st;

int add(int a, int b);
double avg3(int a, int b, int c);
void swap(int& a, int& b);
void printStudent(Student s);

int main() {
    x = 10;
    y = 20;
    z = add(x, y);
    cout << "z = " << endl;
    cout << z << endl;
    average = avg3(10, 20, 30);
    cout << "average = " << endl;
    cout << average << endl;
    nums[0] = 1;
    nums[1] = 2;
    nums[2] = 3;
    nums[3] = 4;
    nums[4] = 5;
    sum = 0;
    for (int i = 0; i <= 4; i++) {
        sum = sum + nums[i];
    }
    cout << "sum(nums) = " << endl;
    cout << sum << endl;
    for (int i = 0; i <= 1; i++) {
        for (int j = 0; j <= 2; j++) {
            mat[i][j] = (i * 10) + j;
        }
    }
    cout << "matrix values:" << endl;
    for (int i = 0; i <= 1; i++) {
        for (int j = 0; j <= 2; j++) {
            cout << mat[i][j] << endl;
        }
    }
    isPassed = (average >= 15) && !(sum < 10);
    if (isPassed) {
        message = "PASS";
    } else {
        message = "FAIL";
    }
    cout << "status:" << endl;
    cout << message << endl;
    i = 0;
    while (i < 3) {
        cout << "while i:" << endl;
        cout << i << endl;
        i = i + 1;
    }
    do {
        i = i - 1;
        cout << "repeat i:" << endl;
        cout << i << endl;
    } while (!(i == 0));
    swap(x, y);
    cout << "after swap x:" << endl;
    cout << x << endl;
    cout << "after swap y:" << endl;
    cout << y << endl;
    st.name = "Alice";
    st.age = 22;
    st.grade = average;
    printStudent(st);

    return 0;
}

int add(int a, int b) {
    return a + b;
}

double avg3(int a, int b, int c) {
    // Variable declarations
    double total;

    total = (a + b) + c;
    return total / 3.0;
}

void swap(int& a, int& b) {
    // Variable declarations
    int temp;

    temp = a;
    a = b;
    b = temp;
}

void printStudent(Student s) {
    cout << "Student:" << endl;
    cout << s.name << endl;
    cout << "Age:" << endl;
    cout << s.age << endl;
    cout << "Grade:" << endl;
    cout << s.grade << endl;
}

