// Generated C++ code from Pascal-like algorithm: TestProcedure
// Original algorithm: TestProcedure

// Generated by Pascal-like to C++ Compiler
// DO NOT EDIT THIS FILE DIRECTLY

#include <iostream>
#include <cmath>
#include <string>
using namespace std;

// Global variables
int value = 0;

void increment(int& x);

int main() {
    value = 10;
    increment(value);
    cout << "value:" << endl;
    cout << value << endl;

    return 0;
}

void increment(int& x) {
    x = x + 1;
}

