// Generated C++ code from Pascal-like algorithm: TestLogic
// Original algorithm: TestLogic

// Generated by Pascal-like to C++ Compiler
// DO NOT EDIT THIS FILE DIRECTLY

#include <iostream>
#include <cmath>
#include <string>
using namespace std;

// Global variables
bool a = false;
bool b = false;

int main() {
    a = true;
    b = false;
    if (a && !(b)) {
        cout << "logic ok" << endl;
    } else {
        cout << "logic fail" << endl;
    }

    return 0;
}

