// Generated C++ code from Pascal-like algorithm: TestArray
// Original algorithm: TestArray

// Generated by Pascal-like to C++ Compiler
// DO NOT EDIT THIS FILE DIRECTLY

#include <iostream>
#include <cmath>
#include <string>
using namespace std;

// Global variables
int a[4];
int i = 0;
int sum = 0;

int main() {
    a[0] = 2;
    a[1] = 4;
    a[2] = 6;
    a[3] = 8;
    sum = 0;
    for (int i = 0; i <= 3; i++) {
        sum = sum + a[i];
    }
    cout << "array sum:" << endl;
    cout << sum << endl;

    return 0;
}

