// Generated C++ code from Pascal-like algorithm: TestFor
// Original algorithm: TestFor

// Generated by Pascal-like to C++ Compiler
// DO NOT EDIT THIS FILE DIRECTLY

#include <iostream>
#include <cmath>
#include <string>
using namespace std;

// Global variables
int i = 0;
int sum = 0;

int main() {
    sum = 0;
    for (int i = 1; i <= 5; i++) {
        sum = sum + i;
    }
    cout << "sum 1..5:" << endl;
    cout << sum << endl;

    return 0;
}

